#!/usr/bin/env ruby

require 'rubygems'
require 'json'

config = JSON::parse(ARGV[0])

nitrogen_port  = config['nitrogen_port']
occipital_port = config['occipital_port']

def run_command(array)
  command = array.join(' ');
  puts ''
  puts "Executing: #{command}"
  puts '=' * 80
  result = system(command)
  puts "  [#{result}]"
end

nitrogen = []
nitrogen.push 'cd /home/ubuntu/nitrogen'
nitrogen.push '&&'
nitrogen.push "daemon --delay=10 --limit=0 --attempts=100 --respawn"
nitrogen.push "--name=nitrogen_#{nitrogen_port}"
nitrogen.push '--chdir=/home/ubuntu/nitrogen'
nitrogen.push '--'
nitrogen.push 'sudo -u ubuntu ./server.js /home/ubuntu/nitrogen/storage'
nitrogen.push "#{nitrogen_port} localhost:#{occipital_port}"

run_command(nitrogen)

