#!/usr/bin/env ruby

require 'rubygems'
require 'json'

config = JSON::parse(ARGV[0])

nitrogen_port  = config['nitrogen_port']
occipital_port = config['occipital_port']

system "cd /home/ubuntu/nitrogen/webserver && forever start ./server.js #{nitrogen_port} localhost:#{occipital_port}"
system "echo nitrogen initiated | mail -s \"nitrogen for `hostname` started\" ktlacaelel@gmail.com"

