#!/usr/bin/env ruby

received_time = Time.now.to_f

require 'rubygems'
require 'json'

loaded_time = Time.now.to_f

started_time = JSON::parse(ARGV[0])['startTime']

system "echo received:'#{(received_time * 1000.0) - (started_time * 1000.0)}, loaded: #{(loaded_time * 1000.0) - (started_time * 1000.0)}' >> /tmp/bench.log"

