#!/usr/bin/env node

fs = require('fs');
data = process.argv[2];
eval('hash = ' + data);
diff = process.hrtime(hash.startTime);

fs.appendFile('/tmp/bench.log', (diff[1] / 1000 / 1000) + "\n", function (err) {
  if (err) throw err;
});

